### ISSUE TITLE
WWF Raw 32X not working on 3365b177

### ISSUE THREAD

**Issue by veb-xenon** [libretro/picodrive#258]
> I have merged my repo into lr-picodrive. Please try using the latest build from [here](https://git.libretro.com/libretro/picodrive/-/pipelines), that shouldn't have this problem anymore. 

 _Originally posted by @irixxxx in [#255](https://github.com/libretro/picodrive/issues/255#issuecomment-3606745446)_

Now I've found that WWF Raw 32X doesn't work. It shows blank screen after the initial Sega logo. I've tested on Ares and it works perfectly. Also on Picodrive 2.05 standalone for Windows and played with no issues.

I'm using Retroarch x64 on Windows 11.

**Comment by KamiLordus** [comment]
Same here.

**Comment by irixxxx** [comment]
HINT handling regression, fixed with 2779ac9.

In with the next merge.

**Comment by veb-xenon** [comment]
> HINT handling regression, fixed with [2779ac9](https://github.com/libretro/picodrive/commit/2779ac9bf182649d5b21465f86b190cf0a7b68bd).
> 
> In with the next merge.

It still happens in f0d4a01. Thanks for checking :-)

**Comment by KamiLordus** [comment]
Because f0d4a01 (libretro core) does not contain 2779ac9 in which the problem was fixed.

**Comment by veb-xenon** [comment]
Still not working, as 6248b51 version on Retroarch :(

**Comment by KamiLordus** [comment]
As I wrote earlier, for some reason Picodrive libretro is still not up to date with upstream repository.

**Comment by irixxxx** [comment]
Sorry for that. I was off from PicDrive for a longer time for personal reasons. Still only have reduced capacity for it, but I hope that will further improve shortly.

**Comment by veb-xenon** [comment]
> Sorry for that. I was off from PicDrive for a longer time for personal reasons. Still only have reduced capacity for it, but I hope that will further improve shortly.

Thanks very much for all :-)
